"""首个 SUPER_ADMIN 初始化的稳定操作常量。"""

from typing import Final

SUPER_ADMIN_BOOTSTRAP_AUDIT_ACTION: Final = "BOOTSTRAP_SUPER_ADMIN"
SUPER_ADMIN_BOOTSTRAP_LOCK_NAME: Final = "pinkdoohub:super-admin-bootstrap"
SUPER_ADMIN_BOOTSTRAP_LOCK_TIMEOUT_SECONDS: Final[int] = 10
SUPER_ADMIN_BOOTSTRAP_PASSWORD_ENV: Final = "PINKDOOHUB_BOOTSTRAP_PASSWORD"
SUPER_ADMIN_BOOTSTRAP_SYSTEM_IP: Final = "0.0.0.0"
