"""Inventory 模块固定业务边界与稳定标识。"""

# 库存余额与单次调整量
INVENTORY_STOCK_MIN = 0
INVENTORY_STOCK_MAX = 999_999
INVENTORY_CHANGE_MIN = -INVENTORY_STOCK_MAX
INVENTORY_CHANGE_MAX = INVENTORY_STOCK_MAX

# 管理员调整输入
INVENTORY_REASON_MIN_LENGTH = 1
INVENTORY_REASON_MAX_LENGTH = 256
INVENTORY_IDEMPOTENCY_KEY_MIN_LENGTH = 1
INVENTORY_IDEMPOTENCY_KEY_MAX_LENGTH = 128
INVENTORY_IDEMPOTENCY_KEY_PATTERN = r"^[\x21-\x7E](?:[\x20-\x7E]{0,126}[\x21-\x7E])?$"
INVENTORY_ADMIN_IDEMPOTENCY_PREFIX = "inventory:admin:adjust:"
INVENTORY_ORDER_DEDUCTION_IDEMPOTENCY_KEY = (
    "inventory:order:{order_id}:deduct:product:{product_id}"
)
INVENTORY_ORDER_DEDUCTION_REASON = "Order stock deduction"
INVENTORY_ORDER_RESTORE_IDEMPOTENCY_KEY = (
    "inventory:order:{order_id}:restore:product:{product_id}"
)
INVENTORY_ORDER_RESTORE_REASON = "Order cancellation stock restore"

# 数据库与 API 字符串字段容量候选；Model 阶段必须沿用或显式修订契约。
INVENTORY_TRANSACTION_TYPE_MAX_LENGTH = 40
INVENTORY_SOURCE_TYPE_MAX_LENGTH = 30
INVENTORY_IDEMPOTENCY_KEY_DB_MAX_LENGTH = 256

# 顺序审计契约
INVENTORY_AUDIT_TARGET_TYPE = "product"
INVENTORY_AUDIT_ACTION_ADJUST = "ADJUST_INVENTORY"

# 数据库死锁/锁等待的完整事务最大尝试次数（含首次）。
INVENTORY_TRANSACTION_MAX_ATTEMPTS = 3
INVENTORY_RETRYABLE_MYSQL_ERROR_CODES = frozenset({1205, 1213})
