"""Product 模块字段校验常量。"""

from decimal import Decimal

# 商品基本信息
PRODUCT_NAME_MIN_LENGTH = 1
PRODUCT_NAME_MAX_LENGTH = 100
PRODUCT_DESCRIPTION_MAX_LENGTH = 2000
PRODUCT_SEARCH_KEYWORD_MAX_LENGTH = 100

# 金额（单位：元）
PRODUCT_PRICE_MIN_EXCLUSIVE = Decimal("0.00")
PRODUCT_PRICE_MAX = Decimal("99999.00")
PRODUCT_PRICE_DECIMAL_PLACES = 2
PRODUCT_PRICE_PATTERN = r"^\d+(?:\.\d{1,2})?$"

# 体验 Option
MIN_DURATION_MINUTES = 1
MIN_PARTICIPANTS = 1

# 套装库存与图片排序
MIN_STOCK = 0
MIN_IMAGE_SORT = 0
