"""桌台二维码开台与计时的冻结业务常量。"""

TABLE_COUNT = 30
TABLE_NO_PREFIX = "T"
TABLE_NO_LENGTH = 3
TABLE_NO_PATTERN = r"^T(?:0[1-9]|[12][0-9]|30)$"
TABLE_DISPLAY_NAME_MAX_LENGTH = 50

TABLE_QR_TOKEN_LENGTH = 32
TABLE_QR_TOKEN_PATTERN = r"^[A-Za-z0-9]{32}$"
TABLE_QR_TOKEN_ALPHABET = (
    "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789"
)

TABLE_SESSION_NO_PREFIX = "TS"
TABLE_SESSION_NO_ULID_LENGTH = 26
TABLE_SESSION_NO_LENGTH = 28
TABLE_SESSION_NO_PATTERN = r"^TS[0-9A-HJKMNP-TV-Z]{26}$"
TABLE_SESSION_NO_CROCKFORD_ALPHABET = "0123456789ABCDEFGHJKMNPQRSTVWXYZ"
TABLE_SESSION_NO_TIMESTAMP_BITS = 48
TABLE_SESSION_NO_RANDOM_BYTES = 10
TABLE_SESSION_NO_GENERATION_MAX_ATTEMPTS = 3

TABLE_PAYMENT_WINDOW_MINUTES = 15
TABLE_TIMER_BUFFER_MINUTES = 10
TABLE_ADMIN_REASON_MAX_LENGTH = 200
TABLE_IDEMPOTENCY_KEY_MAX_LENGTH = 128
TABLE_IDEMPOTENCY_KEY_DB_MAX_LENGTH = 256
TABLE_CLAIM_IDEMPOTENCY_PREFIX = "table_claim:"
TABLE_RELEASE_IDEMPOTENCY_PREFIX = "table_release:"
TABLE_FINGERPRINT_LENGTH = 64

TABLE_SESSION_ENUM_MAX_LENGTH = 32
TABLE_SWEEP_BATCH_SIZE = 100

TABLE_AUDIT_TARGET_TYPE = "table_session"
TABLE_AUDIT_ACTION_CREATE = "CREATE_TABLE_SESSION"
TABLE_AUDIT_ACTION_ACTIVATE = "ACTIVATE_TABLE_SESSION"
TABLE_AUDIT_ACTION_RELEASE = "RELEASE_TABLE_SESSION"
TABLE_AUDIT_ACTION_UPDATE = "UPDATE_STORE_TABLE"

TABLE_STATUS_LABELS = {
    "awaiting_payment": "待支付",
    "active": "计时中",
    "closed": "已结束",
}
TABLE_CLOSE_REASON_LABELS = {
    "payment_timeout": "支付超时",
    "time_expired": "计时结束",
    "order_cancelled": "订单已取消",
    "order_completed": "订单已完成",
    "refunded": "订单已退款",
    "admin_released": "管理员释放",
}
TABLE_TIMER_PHASE_LABELS = {
    "experience": "体验中",
    "grace": "缓冲中",
    "ended": "已结束",
}

TABLE_ORDER_INELIGIBLE_REASONS = {
    "no_experience_item",
    "invalid_experience_duration_snapshot",
    "order_not_pending",
    "order_already_settled",
}

TABLE_RESOLVE_RATE_LIMIT = 60
TABLE_RESOLVE_RATE_WINDOW_SECONDS = 60
TABLE_CREATE_USER_RATE_LIMIT = 5
TABLE_CREATE_IP_RATE_LIMIT = 20
TABLE_CREATE_RATE_WINDOW_SECONDS = 15 * 60
TABLE_USER_READ_RATE_LIMIT = 60
TABLE_USER_READ_RATE_WINDOW_SECONDS = 60
