"""Wallet、Payment 与 Refund 模块的固定业务边界。"""

from decimal import Decimal

# 所有资金字段使用 DECIMAL(10,2)。Wallet 的业务余额上限远小于
# 物理容量；Payment/Refund 仍保留完整正金额范围，以承载订单金额。
MONEY_AMOUNT_MAX_DIGITS = 10
MONEY_AMOUNT_DECIMAL_PLACES = 2
MONEY_AMOUNT_MIN = Decimal("0.01")
MONEY_AMOUNT_MAX = Decimal("99999999.99")

# 钱包余额与单次余额变化。
WALLET_BALANCE_MIN = Decimal("0.00")
WALLET_BALANCE_MAX = Decimal("1000.00")
WALLET_CHANGE_MIN = -WALLET_BALANCE_MAX
WALLET_CHANGE_MAX = WALLET_BALANCE_MAX

# 充值单金额；两个边界均包含。
RECHARGE_AMOUNT_MIN = Decimal("1.00")
RECHARGE_AMOUNT_MAX = Decimal("1000.00")

# 稳定字符串字段容量。
WALLET_ENUM_MAX_LENGTH = 32
WALLET_TRANSACTION_TYPE_MAX_LENGTH = 32
WALLET_SOURCE_TYPE_MAX_LENGTH = 32
PAYMENT_ENUM_MAX_LENGTH = 32
FINANCIAL_NUMBER_LENGTH = 28
PAYMENT_NO_PATTERN = r"^PY[0-9A-HJKMNP-TV-Z]{26}$"
RECHARGE_NO_PATTERN = r"^RC[0-9A-HJKMNP-TV-Z]{26}$"
REFUND_NO_PATTERN = r"^RF[0-9A-HJKMNP-TV-Z]{26}$"
PAYMENT_PROVIDER_REFERENCE_MAX_LENGTH = 128
WALLET_REASON_MAX_LENGTH = 256
WALLET_REASON_MIN_LENGTH = 1
WALLET_IDEMPOTENCY_KEY_MIN_LENGTH = 1
WALLET_IDEMPOTENCY_KEY_MAX_LENGTH = 128
WALLET_IDEMPOTENCY_KEY_PATTERN = (
    r"^[\x21-\x7E](?:[\x20-\x7E]{0,126}[\x21-\x7E])?$"
)
WALLET_IDEMPOTENCY_KEY_DB_MAX_LENGTH = 256

# 内部幂等命名空间与审计动作。
WALLET_ADMIN_IDEMPOTENCY_PREFIX = "wallet:admin:adjust:"
WALLET_PAYMENT_IDEMPOTENCY_PREFIX = "payment:wallet:"
ASSISTED_WALLET_ORDER_IDEMPOTENCY_PREFIX = "payment:admin-assisted:"
REFUND_ADMIN_IDEMPOTENCY_PREFIX = "refund:admin:"
WALLET_ORDER_TRANSACTION_KEY = "wallet:payment:{payment_id}:order:{order_id}"
ASSISTED_WALLET_ORDER_TRANSACTION_KEY = (
    "wallet:admin-assisted:{payment_id}:order:{order_id}"
)
WALLET_REFUND_TRANSACTION_KEY = "wallet:refund:{refund_id}:order:{order_id}"
WALLET_AUDIT_TARGET_TYPE = "wallet"
WALLET_AUDIT_ACTION_ADJUST = "ADJUST_WALLET"
PAYMENT_AUDIT_ACTION_PAY_ORDER = "PAY_ORDER"
PAYMENT_AUDIT_ACTION_MANUAL_SETTLEMENT = "REGISTER_MANUAL_PAYMENT"
MANUAL_PAYMENT_IDEMPOTENCY_KEY = "payment:manual:order:{order_id}"
LEGACY_MANUAL_PAYMENT_IDEMPOTENCY_KEY = (
    "payment:legacy-manual:order:{order_id}"
)
REFUND_AUDIT_ACTION_COMPLETE = "REFUND_ORDER"
WALLET_ORDER_PAYMENT_REASON = "Order paid with wallet balance"
ASSISTED_WALLET_ORDER_PAYMENT_REASON = "Admin-assisted order paid with wallet balance"
WALLET_ORDER_REFUND_REASON = "Full order refund returned to wallet"
ORDER_REFUND_WINDOW_DAYS = 30

# MySQL 1205/1213 对完整事务使用全新事务有限重试。
FINANCIAL_TRANSACTION_MAX_ATTEMPTS = 3
FINANCIAL_RETRYABLE_MYSQL_ERROR_CODES = frozenset({1205, 1213})
